<?php

/**
 * PluginNice
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    opNicePlugin
 * @subpackage lib
 * @author     Hiromi Hishida<info@77-web.com>
 * @author     tatsuya ichikawa <ichikawa@tejimaya.com>
 * @version    0.1
 */
abstract class PluginNice extends BaseNice
{
  public function preSave($event)
  {
    $this->_set('foreign_hash', $this->getTable()->generateForeignHash($this->_get('foreign_table'), $this->_get('foreign_id')));
  }
}
